# Generated by Django 3.1 on 2020-08-14 18:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_user',
            fields=[
            ],
            options={
                'ordering': ('username',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='create_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_category', models.CharField(choices=[('1', 'Conferencia'), ('2', 'Seminario'), ('3', 'Curso'), ('4', 'Congreso')], max_length=1)),
                ('event_place', models.CharField(max_length=50)),
                ('event_address', models.CharField(max_length=50)),
                ('event_initial_date', models.DateTimeField()),
                ('event_final_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1)),
                ('event_creation_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(default='recipe_thumbnails/default.png', upload_to='recipe_thumbnails', verbose_name='Imagen')),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
